name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 10.x
          
    - uses: actions/checkout@v2

    - name: Run npm build
      run: npm run build

    # TODO
